### ISSUE TITLE
Listed users and a _hidden_ prefix (pls see inside)

### ISSUE THREAD

**Issue by TobCube** [koninklijke-collective/my_user_management#17]
I'm not sure what the design idea is... but at the moment two "concepts" seems to be mixed:
I thought a "restricted" user-administrator can see ALL users and the restriction to specific user groups only applies to the user groups (that a restricted user-administrator can select).

The current situation is: A user-administrator can see all users that has an "allowed user-group". AND for these users, the user-administrator can maintain only all "allowed user-groups" (which is fine) BUT in addition he can also remove all already saved/selected groups, that he is not "allowed" to maintain. They occur with a "_hidden_" prefix - which seems to be a bug. 

What the perfect solution for us would be: 
User listing only for specified groups (or another kind of filter) - but this is optional (nice to have). And an restricted user-administrator should be allowed ONLY to add and remove the "allowed" groups.

![user-admin_hidden](https://cloud.githubusercontent.com/assets/7976366/15246733/6c5af132-190f-11e6-99af-1ec27f9e5d61.png)

Thanks! Great extension!

**Comment by bmoex** [comment]
Hi @TobCube,

This was intentionally made this way. The reason is to (avoid) a lot of core hooks to check if the saved groups should be kept at each save.

This can be avoided by configuring groups as role, which include sub roles etc. So only a 'role' is assigned to the user.

I understand your request, but to keep it low maintenance I would avoid fixing this issue :-)

Kind regards,

Benjamin Serfhos

**Comment by bmoex** [comment]
Should be fixed in the v4 release. The group selection list is now custom generated.
